{{#specInfo}}
{{#metaInfo}}
CC=clang
CFLAGS=-O3 -Wall -Wextra -std=c11 -pedantic
PROG=run_tests

CFILES := cauterize.c {{cLibName}}.c {{cLibName}}_meta.c {{cLibName}}_assertions.c socket99.c
HFILES := cauterize.h {{cLibName}}.h {{cLibName}}_meta.h socket99.h greatest.h

all: $(PROG)
clean:
	rm $(PROG)

$(PROG): $(HFILES) $(CFILES)
	$(CC) $(CFLAGS) $(CFILES) -o $@
{{/metaInfo}}
{{/specInfo}}
