{{#specInfo}}
{{#metaInfo}}
CC=clang
CFLAGS=-O3 -Wall -Wextra -std=c11 -pedantic
TEST_PROG=run_tests
CLIENT_PROG=test_client

CFILES := cauterize.c {{cLibName}}.c {{cLibName}}_meta.c
HFILES := cauterize.h {{cLibName}}.h {{cLibName}}_meta.h

all: $(TEST_PROG) $(CLIENT_PROG)
clean:
	rm $(TEST_PROG) $(CLIENT_PROG)

$(TEST_PROG): $(HFILES) $(CFILES) greatest.h assertions.c
	$(CC) $(CFLAGS) $(CFILES) assertions.c -o $@

$(CLIENT_PROG): $(HFILES) $(CFILES)
	$(CC) $(CFLAGS) $(CFILES) test_client.c -o $@
{{/metaInfo}}
{{/specInfo}}
